spring:
  datasource:
    url: jdbc:h2:mem:maindb

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none



  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: maindb

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.makarov.mongock.changelog

  mongo-db:
    write-concern:
      journal: false
    read-concern: local

    batch:
      job:
        enabled: false



