spring:
  datasource:
    url: jdbc:h2:mem:maindb
#  sql:
#    init:
#      mode: always
#      schema-locations: schema.sql
#      data-locations: data.sql
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      port: 8081
#      settings:
#        web-allow-others: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true



